### ISSUE TITLE
Erro de escrita em Violencia Rio de Janeiro.ipynb

### ISSUE THREAD

**Issue by Pteroto** [rogeriochaves/notebooks#1]
Na frase: Parece que a violência está aumentando não é mesmo? Mas espera um momento, a população do Rio também cresce a cada ano, o que aconte se levarmos o crescimento da população em conta também?

"aconte" deveria ser "acontece"

antes do In [282]

**Comment by rogeriochaves** [comment]
hahaha valeu, corrigido 👍
